"""empty message

Revision ID: dce0acb50bb2
Revises: 
Create Date: 2023-11-17 00:22:43.680316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce0acb50bb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('short_path', sa.VARCHAR(length=8), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('cookies', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shorturl',
    sa.Column('short_path', sa.VARCHAR(length=8), nullable=False),
    sa.Column('full_url', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shorturl_short_path'), 'shorturl', ['short_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shorturl_short_path'), table_name='shorturl')
    op.drop_table('shorturl')
    op.drop_table('click')
    # ### end Alembic commands ###
